# Generated by Django 2.2.12 on 2021-05-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amu_bachelor_thesis_app', '0002_auto_20210524_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='lecturer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='amu_bachelor_thesis_app.Lecturer'),
            preserve_default=False,
        ),
    ]
