# Generated by Django 2.2.12 on 2021-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amu_bachelor_thesis_app', '0003_thesis_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
    ]
