# Generated by Django 2.2.12 on 2021-05-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amu_bachelor_thesis_app', '0004_thesis_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amu_bachelor_thesis_app.Student'),
        ),
    ]
