# Generated by Django 2.2.12 on 2021-05-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amu_bachelor_thesis_app', '0005_auto_20210526_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_at', models.DateTimeField()),
                ('edited_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amu_bachelor_thesis_app.Lecturer')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amu_bachelor_thesis_app.Student')),
            ],
        ),
    ]
