# Generated by Django 2.2.12 on 2021-05-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amu_bachelor_thesis_app', '0007_auto_20210526_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_seen', models.BooleanField()),
                ('lecturer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amu_bachelor_thesis_app.Lecturer')),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amu_bachelor_thesis_app.Student')),
                ('thesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amu_bachelor_thesis_app.Thesis')),
                ('thesis_proposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amu_bachelor_thesis_app.ThesisProposition')),
            ],
        ),
    ]
