# Generated by Django 2.2.12 on 2021-05-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amu_bachelor_thesis_app', '0009_auto_20210527_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'STUDENT_CREATED_PROPOSITION'), (2, 'STUDENT_DISCARDED_PROPOSITION'), (3, 'STUDENT_EDITED_PROPOSITION'), (4, 'STUDENT_SELECTED_THESIS'), (5, 'STUDENT_UNSELECTED_THESIS'), (51, 'LECTURER_EDITED_THESIS'), (52, 'LECTURER_ACCEPTED_PROPOSITION'), (53, 'LECTURER_DISCARDED_PROPOSITION')], default=1),
            preserve_default=False,
        ),
    ]
